#cloud-config
ssh_pwauth: false

users:
  - name: ${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${user_pubkey}

  - name: ${agent_user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${agent_pubkey}

chpasswd:
  expire: false

%{ if vm_ip != "" ~}
network:
  version: 2
  ethernets:
    eth0:
      addresses:
        - ${vm_ip}/${vm_netmask}
      gateway4: ${vm_gateway}
%{ endif ~}

%{ if runcmd != "" ~}
runcmd:
%{ for cmd in split("\n", runcmd) ~}
  - ${cmd}
%{ endfor ~}
%{ endif ~}