#cloud-config
hostname: ${servername}
ssh_pwauth: false

users:
  - name: ${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${user_pubkey}

  - name: ${agent_user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${agent_pubkey}

chpasswd:
  expire: false

runcmd:
  # === machine-id の重複（IP重複）を防止する処理を追加 ===
  - rm -f /etc/machine-id /var/lib/dbus/machine-id
  - systemd-machine-id-setup
  - ln -sf /etc/machine-id /var/lib/dbus/machine-id
  - netplan apply
%{ if runcmd != "" ~}
%{ for cmd in split("\n", runcmd) ~}
  - ${cmd}
%{ endfor ~}
%{ endif ~}
